-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:8889
-- Généré le : mar. 10 jan. 2023 à 22:05
-- Version du serveur :  5.7.34
-- Version de PHP : 7.4.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `ecoConception`
--

-- --------------------------------------------------------

--
-- Structure de la table `post`
--

CREATE TABLE `post` (
  `id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `body` mediumtext,
  `exemple` mediumtext,
  `main_tag` varchar(30) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `post`
--

INSERT INTO `post` (`id`, `title`, `body`, `exemple`, `main_tag`, `created_at`, `updated_at`) VALUES
(1, 'Optimiser la taille des fichiers', 'Utiliser des outils de minification pour réduire la taille des fichiers HTML, CSS et JavaScript afin de réduire le temps de chargement des pages et de limiter l\'utilisation de la bande passante.', 'Utiliser des outils tels que Minify ou Closure Compiler pour minifier les fichiers HTML, CSS et JavaScript avant de les mettre en ligne.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(2, 'Utiliser des images en format WebP', 'Utiliser des images en format WebP au lieu de formats traditionnels comme JPEG ou PNG pour réduire la taille des fichiers et améliorer les performances de l\'application.', 'Utiliser l\'outil de conversion de Google pour convertir les images au format WebP avant de les intégrer à l\'application.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(3, 'Utiliser un CDN', 'Utiliser un Content Delivery Network (CDN) pour servir les fichiers statiques (images, fichiers CSS, fichiers JavaScript, etc.) afin de réduire la charge sur le serveur et d\'améliorer les performances de l\'application.', 'Utiliser un service de CDN tel que Cloudflare ou Akamai pour servir les fichiers statiques de l\'application.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(4, 'Utiliser un cache de navigateur', 'Utiliser un cache de navigateur pour stocker les fichiers statiques de l\'application afin de réduire le temps de chargement des pages et de limiter l\'utilisation de la bande passante.', 'Utiliser des en-têtes HTTP tels que Cache-Control ou Expires pour indiquer au navigateur quels fichiers peuvent être mis en cache et pour combien de temps.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(5, 'Optimiser les requêtes serveur', 'Optimiser les requêtes serveur en utilisant des techniques telles que le filtrage, le tri et l\'agrégation afin de réduire le nombre de requêtes nécessaires et améliorer les performances de l\'application.', 'Utiliser des indexes dans la base de données pour améliorer les performances des requêtes de sélection, ou utiliser des agrégats pour réduire le nombre de lignes renvoyées par une requête.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(6, 'Optimiser les requêtes client', 'Optimiser les requêtes client en utilisant des techniques telles que la mise en cache côté client ou la délégation de certaines tâches au client afin de réduire le nombre de requêtes nécessaires et améliorer les performances de l\'application.', 'Utiliser des en-têtes HTTP tels que ETag ou Last-Modified pour mettre en cache côté client les réponses aux requêtes, ou utiliser des techniques de délégation de traitement telles que le MapReduce pour déléguer certaines tâches au client.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(7, 'Utiliser une architecture éco-responsable', 'Utiliser une architecture éco-responsable qui permet de répartir la charge de traitement sur plusieurs serveurs et de réduire la consommation d\'énergie.', 'Utiliser une architecture de type microservices ou de type conteneurisée pour répartir la charge de traitement sur plusieurs serveurs.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(8, 'Utiliser un système de gestion de la consommation d\'énergie', 'Utiliser un système de gestion de la consommation d\'énergie qui permet de surveiller et de réguler la consommation d\'énergie des serveurs et des équipements informatiques afin de réduire la consommation d\'énergie et de protéger l\'environnement.', 'Utiliser un outil de gestion de la consommation d\'énergie tel que IPMI ou PDU pour surveiller et réguler la consommation d\'énergie des serveurs et des équipements informatiques.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(9, 'Utiliser des technologies éco-responsables', 'Utiliser des technologies éco-responsables qui permettent de réduire la consommation d\'énergie et de protéger l\'environnement.', 'Utiliser des technologies telles que le Cloud computing ou l\'edge computing pour externaliser la gestion de la consommation d\'énergie et réduire l\'empreinte écologique de l\'application.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(10, 'Mesurer et surveiller l\'impact écologique de l\'application', 'Mesurer et surveiller l\'impact écologique de l\'application afin de pouvoir identifier les points de progrès et de mettre en place des actions pour réduire cet impact.', 'Utiliser des outils de mesure de l\'empreinte carbone tels que Carbon Footprint ou Greenhouse Gas Protocol pour mesurer l\'impact écologique de l\'application et mettre en place des actions pour le réduire.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(11, 'Utiliser des frameworks modernes et performants', 'Utiliser des frameworks modernes et performants qui permettent de développer rapidement et efficacement une application web moderne.', 'Utiliser des frameworks tels que React ou Angular pour le développement de l\'interface utilisateur, ou utiliser des frameworks tels que Flask ou Django pour le développement du backend.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(12, 'Utiliser une architecture moderne et scalable', 'Utiliser une architecture moderne et scalable qui permet de développer une application qui s\'adapte aux besoins de l\'utilisateur et qui peut évoluer facilement au fil du temps.', 'Utiliser une architecture de type microservices ou de type conteneurisée pour développer une application qui peut être facilement déployée et mise à l\'échelle en fonction des besoins de l\'utilisateur.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(13, 'Utiliser des outils de développement modernes et efficaces', 'Utiliser des outils de développement modernes et efficaces qui permettent de développer rapidement et de manière collaborative une application web moderne.', 'Utiliser des outils de gestion de versions tels que Git ou Mercurial pour gérer le code source de l\'application, ou utiliser des outils de gestion de projet tels que JIRA ou Asana pour suivre l\'avancement du développement de l\'application.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(14, 'Optimiser l\'expérience utilisateur', 'Optimiser l\'expérience utilisateur en proposant un parcours fluide et en limitant les temps de chargement des pages pour réduire l\'utilisation de la bande passante et l\'impact environnemental de l\'application.', 'Utiliser des techniques de chargement différé pour ne charger que les éléments nécessaires au parcours de l\'utilisateur, ou utiliser des techniques de compression pour réduire la taille des fichiers transmis entre le serveur et le client.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(15, 'Utiliser des interfaces utilisateur éco-responsables', 'Utiliser des interfaces utilisateur éco-responsables qui permettent de réduire l\'impact environnemental de l\'application en limitant l\'utilisation de ressources et en proposant un design épuré et éco-responsable.', 'Utiliser des interfaces utilisateur qui ne nécessitent pas de plugin ou de logiciel externe pour fonctionner, ou utiliser des interfaces qui respectent les principes de l\'accessibilité et de l\'inclusion.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(16, 'Promouvoir l\'adoption de bonnes pratiques écologiques', 'Promouvoir l\'adoption de bonnes pratiques écologiques au sein de l\'application en proposant des fonctionnalités qui encouragent l\'utilisateur à adopter des comportements éco-responsables.', 'Utiliser des fonctionnalités de tracking de l\'empreinte carbone pour sensibiliser l\'utilisateur à son impact environnemental, ou mettre en place des systèmes de gamification pour encourager l\'utilisateur à adopter des comportements éco-responsables.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(17, 'Utiliser des technologies éco-responsables', 'Utiliser des technologies éco-responsables qui permettent de réduire l\'impact environnemental de l\'application et de promouvoir une économie circulaire.', 'Utiliser des technologies telles que le Cloud computing ou l\'edge computing pour externaliser la gestion de la consommation d\'énergie et réduire l\'empreinte écologique de l\'application.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(18, 'Mesurer et surveiller l\'impact écologique de l\'application', 'Mesurer et surveiller l\'impact écologique de l\'application afin de pouvoir identifier les points de progrès et de mettre en place des actions pour réduire cet impact.', 'Utiliser des outils de mesure de l\'empreinte carbone tels que Carbon Footprint ou Greenhouse Gas Protocol pour mesurer l\'impact écologique de l\'application et mettre en place des actions pour le réduire.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(19, 'Utiliser des polices de caractères éco-responsables', 'Utiliser des polices de caractères éco-responsables qui permettent de réduire l\'impact environnemental de l\'application et de promouvoir une économie circulaire.', 'Utiliser des polices de caractères gratuites et open source telles que Open Sans ou Lato qui respectent les principes de l\'économie circulaire et qui sont optimisées pour le web.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(20, 'Limiter le nombre de polices de caractères utilisées', 'Limiter le nombre de polices de caractères utilisées afin de réduire la taille des fichiers et de limiter l\'utilisation de la bande passante.', 'Limiter le nombre de polices de caractères utilisées dans l\'application à 2 ou 3 au maximum, en privilégiant des polices polyvalentes qui s\'adaptent à différents contextes et usages.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(21, 'Optimiser les requêtes SQL', 'Optimiser les requêtes SQL ou DQL afin de réduire le temps d\'exécution et de limiter l\'utilisation de ressources serveur.', 'Utiliser des index pour accélérer les requêtes, ou utiliser des jointures judicieusement pour limiter le nombre de requêtes nécessaires.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(22, 'Limiter le nombre de requêtes SQL', 'Limiter le nombre de requêtes SQL ou DQL en utilisant des techniques de cache ou en préchargeant les données pour réduire l\'utilisation de ressources serveur.', 'Utiliser des techniques de cache telles que Redis ou Memcached pour mettre en cache les résultats de requêtes fréquemment exécutées, ou précharger les données dans des structures de données en mémoire pour éviter de devoir exécuter des requêtes à chaque demande de l\'utilisateur.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(23, 'Utiliser les bons types de données', 'Utiliser les bons types de données pour stocker les informations dans la base de données afin de réduire la taille des fichiers et d\'optimiser les performances de la base de données.', 'Utiliser des types de données tels que INT ou VARCHAR plutôt que des types de données plus lourds tels que BLOB ou TEXT lorsque cela est possible.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(24, 'Optimiser la structure de la base de données', 'Optimiser la structure de la base de données en utilisant des clés étrangères et en créant des indexes judicieusement afin de réduire le temps d\'exécution des requêtes et d\'optimiser les performances de la base de données.', 'Utiliser des clés étrangères pour créer des relations entre les tables de la base de données et éviter les doublons, ou créer des indexes sur les champs fréquemment utilisés dans les requêtes pour accélérer leur exécution.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(25, 'Choisir un hébergeur éco-responsable', 'Choisir un hébergeur éco-responsable qui utilise des technologies écologiques et qui a une politique de développement durable.', 'Choisir un hébergeur qui utilise des centres de données éco-responsables alimentés en énergie renouvelable, ou qui a mis en place des programmes de compensation carbone pour compenser l\'empreinte carbone de ses activités.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(26, 'Optimiser l\'utilisation des ressources de l\'hébergeur', 'Optimiser l\'utilisation des ressources de l\'hébergeur en utilisant des technologies telles que le Cloud computing ou l\'edge computing pour externaliser la gestion de la consommation d\'énergie et réduire l\'empreinte écologique de l\'application.', 'Utiliser des technologies de Cloud computing telles que Amazon Web Services ou Microsoft Azure pour externaliser la gestion de la consommation d\'énergie et réduire l\'empreinte écologique de l\'application, ou utiliser des technologies d\'edge computing telles que Cloudflare pour réduire la distance entre les utilisateurs et les serveurs et accélérer les temps de chargement.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(27, 'Optimiser la vitesse de chargement des pages', 'Optimiser la vitesse de chargement des pages afin de réduire le temps d\'attente de l\'utilisateur et de limiter l\'utilisation de la bande passante.', 'Utiliser des outils de minification pour réduire la taille des fichiers HTML, CSS et JavaScript, ou utiliser des techniques de lazy loading pour ne charger les images et les vidéos qu\'au moment où l\'utilisateur en a besoin.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(28, 'Créer une interface utilisateur intuitive et facile à utiliser', 'Créer une interface utilisateur intuitive et facile à utiliser afin de simplifier l\'expérience de l\'utilisateur et de réduire le temps de formation et de familiarisation avec l\'application.', 'Utiliser des conventions d\'interface utilisateur connues et éprouvées, ou utiliser des outils de test utilisateur pour évaluer la facilité d\'utilisation de l\'interface et identifier les points de progrès.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(29, 'Impliquer les utilisateurs dans le processus de conception', 'Impliquer les utilisateurs dans le processus de conception afin de prendre en compte leurs besoins et leurs attentes et de créer une application qui réponde véritablement à leurs attentes.', 'Mener des entretiens avec les utilisateurs, organiser des focus groupes ou utiliser des techniques de design thinking pour inclure les utilisateurs dans le processus de conception de l\'application.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(30, 'Tester l\'application auprès d\'utilisateurs avant la mise en production', 'Tester l\'application auprès d\'utilisateurs avant la mise en production afin de s\'assurer que l\'interface est intuitive et facile à utiliser, et d\'identifier tout problème de performance ou de fonctionnement.', 'Utiliser des outils de test utilisateur pour obtenir des retours d\'utilisateurs sur l\'application et identifier les points de progrès, ou utiliser des outils de test de performance pour mesurer les temps de chargement et identifier les goulots d\'étranglement.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(31, 'Optimiser l\'utilisation de la couleur', 'Optimiser l\'utilisation de la couleur afin de réduire la consommation d\'énergie et de simplifier l\'interface pour l\'utilisateur.', 'Limiter le nombre de couleurs utilisées dans l\'interface pour réduire la charge sur les processeurs et les écrans, utiliser des couleurs qui sont visuellement agréables et moins gourmandes en énergie, ou utiliser des palettes de couleurs prédéfinies pour garantir une harmonie visuelle et une utilisation optimale de l\'énergie.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(32, 'Utiliser des polices de caractères lisibles et adaptées à l\'interface', 'Utiliser des polices de caractères lisibles et adaptées à l\'interface afin de faciliter la lecture et de rendre l\'interface plus agréable à utiliser, tout en réduisant la consommation d\'énergie.', 'Utiliser des polices de caractères sans-serif pour le contenu principal, qui sont plus lisibles et moins gourmandes en énergie, ou utiliser des polices de caractères avec des traits épais pour les titres et les éléments visuels pour les mettre en valeur tout en limitant la consommation d\'énergie.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(33, 'Optimiser la qualité et la taille des images', 'Optimiser la qualité et la taille des images afin de réduire le temps de chargement des pages et de limiter l\'utilisation de la bande passante.', 'Utiliser des outils de compression et de réduction de la taille des images pour réduire la taille des fichiers sans perdre en qualité, ou utiliser des techniques de lazy loading pour ne charger les images et les vidéos qu\'au moment où l\'utilisateur en a besoin.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(34, 'Utiliser des formats de médias adaptés et éco-responsables', 'Utiliser des formats de médias adaptés et éco-responsables afin de réduire l\'empreinte écologique de l\'application et de garantir une qualité optimale pour l\'utilisateur.', 'Utiliser des formats de médias ouverts et non-propriétaires tels que le format WebM pour les vidéos ou le format WebP pour les images, qui sont plus légers et moins gourmands en énergie que les formats propriétaires.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(35, 'Optimiser la réactivité de l\'interface', 'Optimiser la réactivité de l\'interface afin de rendre l\'application agréable à utiliser et de réduire la consommation d\'énergie.', 'Utiliser des techniques de chargement différé pour ne charger les éléments de l\'interface qu\'au moment où ils sont nécessaires, ou utiliser des techniques de virtualisation pour limiter le nombre d\'éléments affichés à l\'écran en même temps.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(36, 'Utiliser des composants éco-responsables dans l\'interface', 'Utiliser des composants éco-responsables dans l\'interface afin de limiter l\'impact environnemental de l\'application et de garantir une expérience utilisateur agréable.', 'Utiliser des composants de l\'interface qui sont optimisés pour la performance et la consommation d\'énergie, ou utiliser des composants qui sont basés sur des standards ouverts et éco-responsables.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(37, 'Optimiser la taille et la complexité des formulaires', 'Optimiser la taille et la complexité des formulaires afin de rendre l\'application plus rapide et plus facile à utiliser, tout en réduisant la consommation d\'énergie.', 'Limiter le nombre de champs de formulaire et de pages de formulaire, utiliser des champs de formulaire pré-remplis et des éléments de formulaire personnalisés pour simplifier l\'interface, ou utiliser des techniques de validation de données en temps réel pour éviter les soumissions de données incorrectes.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(38, 'Optimiser la soumission de données', 'Optimiser la soumission de données afin de réduire la consommation d\'énergie et de simplifier l\'interface pour l\'utilisateur.', 'Utiliser des techniques de transmission de données asynchrones pour ne soumettre que les données nécessaires et réduire la charge sur les processeurs, ou utiliser des techniques de compression de données pour réduire la taille des données transmises.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(39, 'Optimiser le traitement des données du formulaire', 'Optimiser le traitement des données du formulaire afin de réduire la consommation d\'énergie et d\'améliorer les performances de l\'application.', 'Utiliser des techniques de vérification de données en temps réel pour éviter les traitements inutiles, ou utiliser des techniques de traitement par lots pour regrouper les traitements de données et réduire la charge sur les processeurs.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(40, 'Optimiser le stockage et la gestion des données', 'Optimiser le stockage et la gestion des données afin de réduire l\'empreinte écologique de l\'application et de garantir une qualité de service optimale pour l\'utilisateur.', 'Utiliser des bases de données ouvertes et éco-responsables pour stocker les données, ou utiliser des techniques de compression et de gestion efficace des données pour réduire la taille des données stockées et améliorer les performances de l\'application.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(41, 'Optimiser la taille et le nombre de fichiers joints', 'Optimiser la taille et le nombre de fichiers joints afin de réduire la consommation d\'énergie et d\'améliorer les performances de l\'application.', 'Limiter la taille et le nombre de fichiers joints, utiliser des techniques de compression de fichiers pour réduire la taille des fichiers, ou utiliser des techniques de traitement par lots pour regrouper le traitement de plusieurs fichiers.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(42, 'Utiliser des formats de fichiers éco-responsables', 'Utiliser des formats de fichiers éco-responsables afin de réduire l\'empreinte écologique de l\'application et de garantir une qualité optimale pour l\'utilisateur.', 'Utiliser des formats de fichiers ouverts et non-propriétaires pour les fichiers joints, qui sont plus légers et moins gourmands en énergie que les formats propriétaires.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(43, 'Utiliser des balises sémantiques', 'Utiliser des balises sémantiques afin de rendre le code HTML plus lisible et plus facile à comprendre pour les humains et les machines, tout en réduisant la consommation d\'énergie.', 'Utiliser des balises de titres, de paragraphes, de listes et d\'autres balises sémantiques au lieu de div et de span pour structurer le contenu de l\'application.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(44, 'Optimiser la longueur et la complexité du code HTML', 'Optimiser la longueur et la complexité du code HTML afin de rendre l\'application plus rapide et plus facile à maintenir, tout en réduisant la consommation d\'énergie.', 'Utiliser des frameworks comme React, Angular ou Vue pour générer du code HTML optimisé, ou utiliser des librairies comme Handlebars ou Mustache pour créer des templates HTML modifiables et réutilisables.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(45, 'Utiliser un préprocesseur de feuilles de style', 'Utiliser un préprocesseur de feuilles de style afin de rendre le code CSS plus lisible et plus facile à maintenir, tout en réduisant la consommation d\'énergie.', 'Utiliser des préprocesseurs de feuilles de style tels que Sass, Less ou Stylus pour ajouter des fonctionnalités avancées au CSS et rendre le code plus concis et plus maintenable.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(46, 'Utiliser un framework CSS', 'Utiliser un framework CSS afin de simplifier le développement de l\'interface utilisateur et de réduire la consommation d\'énergie en utilisant des code pré-écrit et testé, et en limitant les ressources serveur et client nécessaires à la gestion de l\'interface.', 'Utiliser des frameworks CSS tels que Bootstrap, Foundation ou Materialize pour ajouter rapidement une structure et une apparence professionnelles à l\'application, ou utiliser des frameworks CSS spécialisés tels que Bulma ou Semantic UI pour ajouter des éléments spécifiques à l\'interface.', 'front', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(47, 'Utiliser le type de données le plus adapté', 'Utiliser le type de données le plus adapté afin de réduire la consommation de mémoire et d\'améliorer les performances de l\'application.', 'Utiliser des types de données spécifiques pour les nombres (comme \'INT\' ou \'DECIMAL\'), pour les chaînes de caractères (comme \'VARCHAR\' ou \'TEXT\'), pour les dates (comme \'DATE\' ou \'DATETIME\') et pour les booléens (comme \'BOOLEAN\' ou \'BIT\') afin de stocker les données de manière optimale.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(48, 'Utiliser l\'indexation efficacement', 'Utiliser l\'indexation efficacement afin de réduire la consommation de mémoire et d\'améliorer les performances de l\'application.', 'Utiliser des index pour les colonnes qui sont fréquemment utilisées dans les requêtes de sélection, d\'ordre ou de jointure, mais éviter d\'utiliser des index pour les colonnes qui sont rarement utilisées ou qui sont souvent mises à jour, afin de limiter l\'utilisation de la mémoire et de l\'espace disque.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(49, 'Utiliser des requêtes paramétrées', 'Utiliser des requêtes paramétrées afin de réduire la consommation de mémoire et d\'améliorer les performances de l\'application.', 'Utiliser des requêtes paramétrées pour les requêtes qui sont exécutées plusieurs fois, afin de réduire la consommation de mémoire et d\'améliorer les performances de l\'application.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57'),
(50, 'Utiliser des requêtes asynchrones', 'Utiliser des requêtes asynchrones afin de réduire la consommation de mémoire et d\'améliorer les performances de l\'application.', 'Utiliser des requêtes asynchrones pour les requêtes qui sont exécutées plusieurs fois, afin de réduire la consommation de mémoire et d\'améliorer les performances de l\'application.', 'back', '2023-01-10 21:22:52', '2023-01-10 21:32:57');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `post`
--
ALTER TABLE `post`
  ADD PRIMARY KEY (`id`) USING BTREE;

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `post`
--
ALTER TABLE `post`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
